server:
  port: '9090'

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/microservice
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: USER-SERVICE